# Generated by Django 4.2.6 on 2023-10-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.CharField(max_length=500, null=True, verbose_name='О клубе')),
                ('photo', models.ImageField(null=True, upload_to='img/club', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500, verbose_name='О эксперте')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('links', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.CharField(max_length=500, null=True, verbose_name='О мероприятии')),
                ('target', models.CharField(max_length=500, null=True, verbose_name='Цель')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('photo', models.ImageField(null=True, upload_to='img/quest', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('info', models.CharField(max_length=500, null=True, verbose_name='О теме')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.CharField(max_length=100, null=True, verbose_name='О мероприятии')),
                ('shedule', models.DateTimeField(null=True, verbose_name='Время')),
                ('photo', models.ImageField(null=True, upload_to='img/event', verbose_name='Фото')),
                ('status', models.IntegerField(choices=[(1, 'Будет'), (2, 'Идет'), (3, 'Прошло')], null=True, verbose_name='Статус')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basefunc.expert', verbose_name='Эксперт')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basefunc.topic', verbose_name='Тема')),
            ],
        ),
    ]
