# Generated by Django 4.2.6 on 2023-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0002_status_event_info_event_photo_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
