# Generated by Django 4.2.6 on 2023-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0003_topic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
