# Generated by Django 4.2.6 on 2023-10-21 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basefunc', '0004_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquest',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='userquest',
            name='user',
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
        migrations.DeleteModel(
            name='UserQuest',
        ),
    ]
