# Generated by Django 4.2.6 on 2023-10-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0004_alter_event_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Будет'), (2, 'Идет'), (3, 'Прошло')], null=True, verbose_name='Статус'),
        ),
    ]
