# Generated by Django 4.2.6 on 2023-10-21 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basefunc', '0006_remove_event_topic_event_club_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('rating', models.IntegerField(choices=[(1, 'Не понравилось'), (2, 'Не совсем понравилось...'), (3, 'Можно было и лучше'), (4, 'В принципе неплохо.'), (5, 'Всем доволен!')], verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basefunc.event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
