# Generated by Django 4.2.6 on 2023-10-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='youtube.com', max_length=200, verbose_name='Ссылка на мероприятие'),
        ),
    ]
