# Generated by Django 4.2.6 on 2023-10-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0008_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video-lecture/%Y/%m/%d/', verbose_name='Запись встречи')),
                ('text_materials', models.CharField(max_length=200, verbose_name='Ссылка на доп. материалы')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basefunc.event', verbose_name='Событие')),
            ],
        ),
    ]
