# Generated by Django 4.2.6 on 2023-10-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefunc', '0009_meetmaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetmaterials',
            name='text_materials',
        ),
        migrations.AddField(
            model_name='event',
            name='text_materials',
            field=models.CharField(default='7-8', max_length=200, verbose_name='Ссылка на доп. материалы'),
        ),
    ]
