# Generated by Django 4.2.6 on 2023-10-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='lock_other',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='visible',
        ),
    ]
